<?xml version="1.0" encoding="ISO-8859-1"?>
<ncl  id="example03" xmlns="http://www.ncl.org.br/NCL3.0/EDTVProfile">
<body>
  <port id="pMainPort" component="image" />
  <media id="image" src="media/backgroundPassive.png">
    <property name="left" value="525" />
    <property name="top" value="100" />
    <property name="width" value="25%" />
    <property name="heigth" value="25%" />
  </media>
</body>
</ncl>